### ISSUE TITLE
task affinity and the main task

### ISSUE THREAD

**Issue by fhoenig** [RichieSams/FiberTaskingLib#26] opened 2016-12-06 05:30 UTC
I was wondering on how you'd imaging a game engine to use this.

You have the concept of a Main Task which seems to land on arbitrary threads, just like all other task. Can you explain your thoughts on that?

I tried to init GLFW once inside that main task and that caused it to crash, even in moments when it was on the main thread. Now I probably don't want to do system calls inside tasks that run on fibers. However, from using the library it is not clear whether the context switching (register and stack) is robust enough. 

1) What CAN run inside these?
2) can you outline a pseudo main game loop using this (with worst case, OpenGL in use).

**Comment by RichieSams** [comment] 2016-12-06 07:01
GLFW is probably crashing because certain OpenGL OpenGL calls must be made from the same thread that made the window context.

But you bring up a very valid point. I'm going to think it over for the next few days, and see if I can't think of a way to integrate the two.

**Comment by fhoenig** [comment] 2016-12-06 07:12
OpenGL in a different thread is obvious. 
However it also crashes when the task is running on the main thread where the context. 

Also crashes on  basic windows system calls. Like GetModuleNameA. Also when its in the main thread.

In the original presentation, they said that system calls and file IO is kept outside of the task system, which makes sense. 

Your ::Run methods however "owns" the main thread. 
Not sure how you imagine a basic game loop to be composed in this scenario.

**Comment by RichieSams** [comment] 2016-12-06 18:16
Hmm, I'm going to re-watch the presentation, and another presentation that Bungie did about task-based Rendering.

My initial thought would be to have the tasking system threads, a render thread, and a system call thread. The render thread and system call thread would be slept until signalled. This would over-subscribe the cores. My idea would be to use system events to wake the render thread or system call thread, and then sleep the currently active tasking thread. Effectively giving them the core. However, oversubscription with time slicing might end up ok.

Alternatively, you can just set the tasking system to use N - 1 threads, and leave a dedicated render thread. Though, if rendering is light, this has the possibility of wasting core time.

I'm going to fiddle around with the idea this week / weekend, and see what I can come up with. Any suggestions are welcome

**Comment by BrodyHiggerson** [comment] 2017-01-13 12:44
I'll second this - I've had troubles getting RakNet working in my dedicated server when it's started from within the main fiber rather than the vanilla main function. 

`int main(int argc, const char** argv)
{
	AppInit<ServerApplication> app(argc, argv);
	app.PreRun(); // this is a call I have to plum through my entire start-up to get the NetworkSystem to set up RakNet before fiber calls. Feels bad :(

	TaskScheduler::g_taskScheduler->Run(25, mainTask, &app);

	return 0;
}`

**Comment by RichieSams** [comment] 2017-02-25 22:22
After a lot of fiddling, I can confirm that calling kernel functions from within fibers causes a segfault.

**Comment by fhoenig** [comment] 2017-02-25 22:26
Yep. Was pretty naive of me to think it didn't. That's not the point of
writing a task system like that anyway.

**Comment by BrodyHiggerson** [comment] 2017-02-25 22:31
What's the suggested way to handle this? E.g. RakNet start-up does not like
fibers. Should we just initialize and perform all of these calls up-front
before starting the fibers? Open to suggestions :)

**Comment by fhoenig** [comment] 2017-02-25 22:47
I think there is generally no way around architecting your engine in a way
to keep more traditional IO threads for these things. Build a lightweight
abstraction around your network state exchange and implement a messaging
system that lives purely inside your system. Then take advantage of
software threads like these fibers to generate as much "overlap" or latency
hiding for your game code.

What is the promise here anyway?

One would wish get as close to just writing game logic all over the place
and hope for concurrency to be somewhat transparently handled. Which is an
illusion to some degree, except maybe if you have a strictly functional
language.

might be wrong. I'm not as experienced with this as a person having written
multiple custom game engines. I'm biased by doing a lot of GPU compute sort
of parallelism.

**Comment by RichieSams** [comment] 2017-03-20 11:44
I've just updated the base asm files that implement the fiber switches. (See 53018a1c90efa0bc95e1b573346b0852c929da03 and 978f8676c7d8d5ae3e3127d79c73cb904d94bb95) With the small tests that I've done, it seems like GLFW is happy to run inside the MainTask now.

I'm going to do some more tests and see if this will allow all kernel functions to be used.

**Comment by BrodyHiggerson** [comment] 2017-03-20 11:50
Just wanted to say that I really appreciate your continued work on this
library! It definitely makes me more keen to roll it into my project when
it makes sense to do so. I can test this change at some point in the future
on x64 if you need (RakNet start-up).

**Comment by RichieSams** [comment] 2017-03-20 11:54
You're very welcome! I'm just excited that people think it's useful. :P 

I've been hacking on a "Simple GLFW Game Engine" that uses FTL under the covers. I currently have it working with GLFW loop, logic loop, and render loop, in three different threads.

With this newest change, I'm hoping to merge GLFW and logic into one loop, then put rendering on another, so they can overlap. I'll post the code to https://github.com/RichieSams/FiberTaskingLibExamples

**Comment by BrodyHiggerson** [comment] 2017-03-20 11:59
I'll be sure to continue pushing the library to the performance limits.
Only then will I call it useful :P

That sounds like a great example! Looking forward to it.

**Comment by RichieSams** [comment] 2017-03-21 02:21
I pushed some early code: https://github.com/RichieSams/FiberTaskingLibExamples/tree/master/source/simple_game

It isn't any kind of game yet. It just renders a cube endlessly, and sleeps in the update(). But GLFW seems to work fine from inside FiberMain()

**Comment by BrodyHiggerson** [comment] 2017-03-21 03:16
Great, I'll check it out. What were you using for the above profiling,
again? I can see your tags for profiling but can't remember the tool you
use. It looks pretty damn nice!

**Comment by RichieSams** [comment] 2017-05-05 01:46
I'm going to close this, as it seems like the changes to the assembly code have re-enabled outside code to live inside the main loop.

**Closed by RichieSams** 2017-05-05 01:46 UTC
